before:
  hooks:
    - go mod download
builds:
  - binary: hello
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
brews:
  - tap:
      owner: defn
      name: homebrew-taps
    folder: Formula
    homepage:  https://defn.sh/hello
    description: hello
    license: MIT
    install: |-
      bin.install "hello"
    commit_author:
      name: goreleaserbot
      email: iam@defn.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.BUILD_TAG }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
