before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - binary: hello
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
dockers:
  - binaries:
      - hello
    extra_files: []
    goos: linux
    goarch: amd64
    image_templates:
      - "defn/hello:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
  - binaries:
      - hello
    extra_files: []
    goos: linux
    goarch: arm64
    image_templates:
      - "defn/hello:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --platform=linux/arm64/v8
docker_manifests:
  - name_template: "defn/hello:{{ .Version }}"
    image_templates:
      - "defn/hello:{{ .Version }}-amd64"
      - "defn/hello:{{ .Version }}-arm64"
brews:
  - tap:
      owner: defn
      name: homebrew-taps
    folder: Formula
    homepage:  https://defn.sh/hello
    description: hello
    license: MIT
    install: |-
      bin.install "hello"
    commit_author:
      name: goreleaserbot
      email: iam@defn.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.BUILD_TAG }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
