before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - binary: main
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
dockers:
  - binaries:
      - main
    goos: linux
    goarch: amd64
    image_templates:
      - "defn/hello:test"
    skip_push: true
    dockerfile: Dockerfile
    extra_files: []
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
